baseURL = "https://thecloudblog.net"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "The Cloud Blog"
theme = "okayish-blog-fork"
enableGitInfo = true
enableEmoji = true
enableRobotsTXT = true
paginate = 10

[params]
    mainSections = ["post","lab"]
    # These will be used for OpenGraph, Twitter Card and Schema.org
    description = "Articles with â™¥ on Cloud Native, Kubernetes and Open Source by Rahul Rai (t: @rahulrai_in). FOMO? I can send you email updates ğŸ‘. Subscribe."
    homePageDescription = "Cloud Computing, Cloud Native & Kubernetes by Rahul"
    keywords = ["azure", "aws", "cloud", ".NET Core", "Kubernetes", "blog", "tips", "ASP.net", "DevOps", "Web"]

# This is the number of terms within a taxonomy per page
termsPaginate = 50
# Enable/disable share links (Reddit, Twitter and LinkedIn)
shareLinksEnabled = true

[permalinks]
    other = "/:slug"

# Add menu items to the navigation bar as below.
[menu]

    [[menu.main]]
    name = "ğŸ§ Profile"
    weight = 1
    url = "/profile"

    [[menu.main]]
    name = "ğŸ”– Publications"
    weight = 2
    url = "/publications"

    [[menu.main]]
    name = "ğŸ† Affiliations"
    weight = 3
    url = "/affiliations"

[module]
    [[module.mounts]]
        source = "assets/lib/img"
        target = "static/lib/img"

    [[module.mounts]]
        source = "root"
        target = "static"

[social]
    twitter = "rahulrai-in"