baseURL = "https://thecloudblog-v2.netlify.app"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "The Cloud Blog"
theme = "okayish-blog-fork"
enableGitInfo = true
enableEmoji = true
enableRobotsTXT = true

paginate = 100

[params]
    mainSections = ["post","lab"]
    # These will be used for OpenGraph, Twitter Card and Schema.org
    description = "by Rahul Rai"
    keywords = ["azure", "cloud", "blog", "tips", "ASP.net", "DevOps", "Web"]

# This is the number of terms within a taxonomy per page
termsPaginate = 50
# Enable/disable share links (Facebook, Twitter and LinkedIn)
shareLinksEnabled = true

[permalinks]
    other = "/:slug"

# Add menu items to the navigation bar as below.
[menu]

    [[menu.main]]
    name = "whoami"
    weight = 1
    url = "/whoami"

    [[menu.main]]
    name = "Publications"
    weight = 2
    url = "/authors"

[module]
    [[module.mounts]]
        source = "assets/lib/img"
        target = "static/lib/img"

    [[module.mounts]]
        source = "root"
        target = "static"

[social]
    twitter = "rahulrai-in"